language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "${gh_token}"
  local_dir: "$TRAVIS_BUILD_DIR/build/docs"
  on:
    branch: master
after_success:
- gradle generateJavadoc && cp "$TRAVIS_BUILD_DIR/README.md" "$TRAVIS_BUILD_DIR/build/docs"
- gradle jacocoTestReport && bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: QHQiD2MI8Si7+8ZzjfMlsRcQuQYunV5j+fHaXXtWXWfaC84nahvi3lt/+ZKb5GxnNRAYy6kGpPM6TVGlcT3qfmeS/4oIbYX7FUv67Hhd6kvcZ87q3Pz1clas1y6ILSTNmHjUNW3Po7D5Po07uVy3xxsZ4VTbwLDW6n109D1DLngfzGVPFPCbDsrnZzzA2lmHAd9OAo1n3jnq55Ku4YQKqZ1VXjnG2BmEwMOYrQYPgCpgcTLEBISI4iR7TxDixKmhFqKU38mnGTpWl6viiJB4cDZ1EIE9uBtkgzPetl1dpDfVg4yH9cfzvCWDlcjlfltxr3pVrkVRSMAxywFF/rhEMj7qDZYCP1AyMRseuB3nIsTO5csv+KmQfLMV1Mk6neDJprgYPDD3UQZ7HqDy4l3sIK5E80SMpNUSUSHEn0QQvPNQKIbb+Nq0VPF+7GLTnP/y7gMewMOScqR0DGsf463E+btkrasmD5sqPBjjlMWZPZYr2vVqZJDcQhCnzqxfPk1EZyk95MIgZj+zXG7z0hBq/aul5vdVz1oBGNSJNEsENHHOJTm7Jhh8R+DZ1OpY7HW2WuAjdj1s5ZiXqSD28GhmqwcPMUwGikZwW1IQ58kqqvTCE4x1+N49GHjRq6UpDIQ8z4yD0J0EToC9HE7EhrSNl7i8kqMP92WYikbIyJX1ogk=
